name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      #uses: actions/setup-ruby@v1
      uses: ruby/setup-ruby@v1
      # Use ruby/setup-ruby@v1 instead
      # ref.
      #   https://github.com/actions/setup-ruby/issues/64
      #   https://github.com/ruby/setup-ruby
      with:
        ruby-version: 3.1.2
    - name: Build and test with Rake
      run: |
        gem install bundler
        #bundle install --jobs 4 --retry 3
        #bundle exec rake
        # Do nothing here now because sqlite3 gem is cannot be installed and
        # I'm not sure how to do the Rails project test on GitHub Actions.
